edition = "2018"
imports_indent = "Block"
imports_layout = "Mixed"
imports_granularity = "Crate"
wrap_comments = true
format_code_in_doc_comments = true
comment_width = 100             # Default 80
normalize_comments = false
normalize_doc_attributes = false
format_strings = false